# Generated by Django 3.2.16 on 2024-03-19 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0005_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='birthday.tag', verbose_name='Тег'),
        ),
    ]
